### ISSUE TITLE
Bug with enemies revealed by Gas Mask, possibly Mirror too.

### ISSUE THREAD

**Issue by Kazuto88** [wildham0/FFMQRando#17]
Playing a seed that I genned this afternoon, I got the Gas Mask from the vanilla Mirror location in the Icy Pyramid, and the enemies in the pyramid were revealed as a result. It even played the whooshing sound like normal.

The mirror was elsewhere in the Pyramid and did not play any sort of sound when I picked it up. When I got to the volcano, enemies were already revealed as they should have been.

![FFMQR 0 2 25 4242DF3D xm0AAAAAAAA~ 2022-03-19 11 05 33](https://user-images.githubusercontent.com/39844884/159141320-98f83089-0c43-47e8-a0b9-863f2f9d26c2.png) ![FFMQR 0 2 25 4242DF3D xm0AAAAAAAA~ 2022-03-19 11 05 37](https://user-images.githubusercontent.com/39844884/159141321-d68783d2-639c-432a-afa4-d97e00f142bf.png)

Apologies for the character name, I forgot I put it as that, lol.

**Comment by wildham0** [comment]
It's a known issue (it's pretty funny if you trigger it in a village), there should be a fix for it soon.

**Comment by wildham0** [comment]
Should be fixed in 0.3.02 now
