### ISSUE TITLE
Issues with random enemy placement, could cause unbeatable seeds

### ISSUE THREAD

**Issue by Kazuto88** [wildham0/FFMQRando#18]
So the random enemy placement is an interesting idea, though I noticed it doesn't seem to have much logic to it at the moment?
![FFMQR 0 2 25 DDAD2862 uwQAAAAAAAA~ 2022-03-12 17 14 00](https://user-images.githubusercontent.com/39844884/159141445-3cc9ba57-2aee-439d-a785-df6cdce1e0c0.png) ![FFMQR 0 2 25 DDAD2862 uwQAAAAAAAA~ 2022-03-13 03 06 02](https://user-images.githubusercontent.com/39844884/159141446-9f85519b-b853-4b4c-8fc8-cfdcf4bf5dd4.png)

The enemies in these two screenshots are both out-of-bounds of the level, which is more of a quirky thing than a problematic thing.

The problematic thing is in the screenshot below.
![FFMQR 0 2 25 DDAD2862 uwQAAAAAAAA~ 2022-03-12 17 33 19](https://user-images.githubusercontent.com/39844884/159141457-1baf5680-7b15-42be-97a1-afa7264a5aa5.png)

You can't see it directly because I don't have the Mirror, but **there's an enemy between those two chests.** This being a key item chest means it's impossible to get that chest, which would make the seed unbeatable if any one of the go mode items were in it. Random enemy placement will need some minor logic to account for situations such as this.

**Comment by wildham0** [comment]
There's some logic to it but some exceptions need to be added manually, I'll add that position to the excluded tiles. Thanks for your help!

**Comment by Kazuto88** [comment]
Now that I'm thinking about it more, there's a few spots where enemy placement could cause an issue. Is there already logic in place to avoid enemies spawning at ledges where the player usually has to cross?

Also, in the Lava Dome, there are two more spots with chests that you need to jump over to get both:
![Lava Dome 4](https://static.wikia.nocookie.net/finalfantasy/images/6/62/FFMQ_Lava_Dome_Area_4_-_Inside.png)
![Lava Dome 5](https://static.wikia.nocookie.net/finalfantasy/images/d/da/FFMQ_Lava_Dome_Area_5_-_Inside.png)

FF Wiki refers to these as Lava Dome 4 and 5, though I'm not sure if that correlates with any in-game data on it.

**Comment by wildham0** [comment]
Thanks, I did miss the one in the second screenshots.

**Comment by wildham0** [comment]
Seems no error has popped up for a few months now, feature should be pretty safe.
